# Generated by Django 3.2.22 on 2023-12-14 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_tutor_contato'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1)),
                ('especie', models.CharField(choices=[('G', 'Gato'), ('C', 'Cachorro'), ('E', 'Exótico')], max_length=1)),
                ('cor', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='tutor',
            name='pet',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.pet'),
        ),
    ]
